services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./docker/sensor-storage/minio/data:/export

  golang:
    container_name: ${MINIO_CONTROL_CONTAINER_HOST}
    hostname: ${MINIO_CONTROL_HOST}
    tty: true
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./src:/go/src/app
    ports:
      - 8000:8000
